name: sit
on:
  push:
    branches:
      - sit
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.10.0"
      - name: Install npm dependencies
        run: npm install yarn -g && yarn install
      - name: Run build task
        run: npm run build
      - name: copy file  via ssh key
        uses: appleboy/scp-action@master
        with:
          source: "dist/*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/sit/abstract-antdpro/"
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          strip_components: 1
